### PR TITLE
Speed up rebalance plan execution

### PR DESCRIPTION
**Pull request by udaysagar2177**
This speeds up the plan execution step as it will fetch the current plan only for the topics in proposed plan.

### CODE REVIEW

**Comment by udaysagar2177** [comment]
@flavray Let me address your concerns by this weekend, thanks for the review!

**Comment by udaysagar2177** [comment]
@flavray I addressed your comments. The build failed this time at `docker-compose build` step, before executing any tests and the error appears to be a transient one. How can I re-trigger the build?

**Comment by flavray** [comment]
I've kicked off another build, let's see how it goes 🙂

**Comment by udaysagar2177** [comment]
My pleasure, thanks for the quick review!

**Pull request merged**
